import File_System
import Foundation
import Testing

@testable import Workspace_Application

extension Workspace.Context {
    @Suite
    struct Test {
        @Suite struct Unit {}
        @Suite struct `Edge Case` {}
        @Suite struct Integration {}
    }
}

extension Workspace.Context.Test {
    private static let marker =
        "<!-- Generated by `workspace context install`; edit the canonical template in Workspace/Context. -->"

    private static func fixture<Result>(
        _ body: (Workspace.Context) throws -> Result
    ) throws -> Result {
        let base = FileManager.default.temporaryDirectory.appending(path: UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: base) }
        try FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)

        let temporary = try File.Directory(validating: base.path)
        let entry = temporary[directory: "entry"]
        let institute = entry[directory: "swift-institute"]
        let checkout = institute[directory: "Workspace"]
        let templates = checkout[directory: "Context"]
        let publicSkills = institute[directory: "Skills"]
        let internalSkills = institute[directory: "Internal"][directory: "Skills"]
        let engagementSkills = institute[directory: "Engagement"][directory: "Skills"]
        let ruleSkills = entry[directory: "rule-institute"][directory: "Skills"]

        for directory in [
            templates,
            publicSkills,
            internalSkills,
            engagementSkills,
            ruleSkills,
        ] {
            try directory.create.recursive()
        }
        try templates[file: "AGENTS.md"].write.atomic(
            "\(Self.marker)\n# Fixture\n"
        )
        try templates[file: "CLAUDE.md"].write.atomic(
            "\(Self.marker)\n@AGENTS.md\n"
        )

        for (root, name) in [
            (publicSkills, "public-skill"),
            (internalSkills, "internal-skill"),
            (engagementSkills, "engagement-skill"),
            (ruleSkills, "rule-skill"),
        ] {
            let skill = root[directory: try File.Path.Component(name)]
            try skill.create.recursive()
            try skill[file: "SKILL.md"].write.atomic(
                "---\nname: \(name)\ndescription: fixture\n---\n\n# Fixture\n"
            )
        }

        return try body(
            Workspace.Context(root: Workspace.Root(checkout: checkout))
        )
    }
}

extension Workspace.Context.Test.Unit {
    @Test
    func `install materializes documents and every canonical skill source`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()

            #expect(try context.diagnostics().isEmpty)
            #expect(
                try File.System.Link.Read.Target.target(
                    of: context.entry[directory: ".agents"].path / "skills"
                ) == File.Path("../.claude/skills")
            )
            #expect(
                try File.System.Link.Read.Target.target(
                    of: context.entry[directory: ".claude"][directory: "skills"].path
                        / "public-skill"
                ) == File.Path("../../swift-institute/Skills/public-skill")
            )
            #expect(
                try File.System.Link.Read.Target.target(
                    of: context.entry[directory: ".claude"][directory: "skills"].path
                        / "internal-skill"
                ) == File.Path("../../swift-institute/Internal/Skills/internal-skill")
            )
            #expect(
                try File.System.Link.Read.Target.target(
                    of: context.entry[directory: ".claude"][directory: "skills"].path
                        / "engagement-skill"
                ) == File.Path("../../swift-institute/Engagement/Skills/engagement-skill")
            )
            #expect(
                try File.System.Link.Read.Target.target(
                    of: context.entry[directory: ".claude"][directory: "skills"].path
                        / "rule-skill"
                ) == File.Path("../../rule-institute/Skills/rule-skill")
            )
            #expect(
                try File.System.Metadata.Permissions(
                    at: context.entry[file: "AGENTS.md"].path
                ) == .defaultFile
            )
            #expect(
                try File.System.Metadata.Permissions(
                    at: context.entry[file: "CLAUDE.md"].path
                ) == .defaultFile
            )
        }
    }

    @Test
    func `install is idempotent`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            try context.install()

            #expect(try context.diagnostics().isEmpty)
        }
    }

    @Test
    func `install refreshes its generated document`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            try context.root.checkout[directory: "Context"][file: "AGENTS.md"]
                .write.atomic("\(Workspace.Context.Test.marker)\n# Revised fixture\n")
            try context.root.checkout[directory: "Context"][file: "CLAUDE.md"]
                .write.atomic("\(Workspace.Context.Test.marker)\n@Revised.md\n")

            try context.install()

            #expect(try context.diagnostics().isEmpty)
        }
    }

    @Test
    func `install removes a retired generated skill projection`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            let institute = context.entry[directory: "swift-institute"]
            let skill = institute[directory: "Skills"][directory: "public-skill"]
            try skill[file: "SKILL.md"].delete()

            try context.install()

            let claude = context.entry[directory: ".claude"]
            let skills = claude[directory: "skills"]
            #expect(!skills[file: "public-skill"].stat.exists)
            #expect(try context.diagnostics().isEmpty)
        }
    }
}

extension Workspace.Context.Test.`Edge Case` {
    @Test
    func `install rejects malformed canonical skill metadata before projecting`() throws {
        try Workspace.Context.Test.fixture { context in
            let institute = context.entry[directory: "swift-institute"]
            let publicSkills = institute[directory: "Skills"]
            let publicSkill = publicSkills[directory: "public-skill"]
            let skill = publicSkill[file: "SKILL.md"]
            try skill.write.atomic(
                """
                ---
                name: public-skill
                description: fixture
                layer: implementation
                ---
                # Fixture
                """
            )

            #expect(throws: Workspace.Error.self) {
                try context.install()
            }
            #expect(!context.entry[directory: ".claude"].stat.exists)
        }
    }

    @Test
    func `install refuses an unmanaged root document before creating projections`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.entry[file: "AGENTS.md"].write.atomic("# Local instructions\n")

            #expect(throws: Workspace.Error.self) {
                try context.install()
            }
            #expect(
                !context.entry[directory: ".claude"].stat.exists
            )
        }
    }

    @Test
    func `install preserves a user alias into a canonical skill root`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            let alias = context.entry[directory: ".claude"][directory: "skills"].path
                / "user-alias"
            try FileManager.default.createSymbolicLink(
                atPath: alias.description,
                withDestinationPath: "../../swift-institute/Skills/public-skill"
            )

            try context.install()

            #expect(
                try File.System.Link.Read.Target.target(of: alias)
                    == File.Path("../../swift-institute/Skills/public-skill")
            )
            #expect(try context.diagnostics().isEmpty)
        }
    }
}
