import File_System
import Foundation
import Testing

@testable import Workspace_Application

extension Workspace.Context {
    @Suite
    struct Test {
        @Suite struct Unit {}
        @Suite struct `Edge Case` {}
        @Suite struct Integration {}
    }
}

extension Workspace.Context.Test {
    private static let marker =
        "<!-- Generated by `workspace context install`; edit the canonical template in Workspace/Context. -->"

    /// Materializes a hierarchy and an account root that are siblings, never
    /// nested, so nothing here can pass by resolving relative to the checkout.
    ///
    /// - Parameter roots: The canonical skill roots to materialize. The default
    ///   is all four; passing fewer models an account that clones fewer
    ///   repositories, which is every contributor outside the Institute.
    private static func fixture<Result>(
        roots: Set<Swift.String> = [
            "public-skill", "internal-skill", "engagement-skill", "rule-skill",
        ],
        _ body: (Workspace.Context) throws -> Result
    ) throws -> Result {
        let base = FileManager.default.temporaryDirectory.appending(path: UUID().uuidString)
        defer { try? FileManager.default.removeItem(at: base) }
        try FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)

        let temporary = try File.Directory(validating: base.path)
        let home = temporary[directory: "home"]
        let entry = temporary[directory: "entry"]
        let institute = entry[directory: "swift-institute"]
        let checkout = institute[directory: "Workspace"]
        let templates = checkout[directory: "Context"]
        let publicSkills = institute[directory: "Skills"]
        let internalSkills = institute[directory: "Internal"][directory: "Skills"]
        let engagementSkills = institute[directory: "Engagement"][directory: "Skills"]
        let ruleSkills = entry[directory: "rule-institute"][directory: "Skills"]

        let sources = [
            (publicSkills, "public-skill"),
            (internalSkills, "internal-skill"),
            (engagementSkills, "engagement-skill"),
            (ruleSkills, "rule-skill"),
        ].filter { roots.contains($0.1) }

        try home.create.recursive()
        try templates.create.recursive()
        try templates[file: "AGENTS.md"].write.atomic(
            "\(Self.marker)\n# Fixture\n"
        )
        try templates[file: "CLAUDE.md"].write.atomic(
            "\(Self.marker)\n@AGENTS.md\n"
        )

        for (root, name) in sources {
            let skill = root[directory: try File.Path.Component(name)]
            try skill.create.recursive()
            try skill[file: "SKILL.md"].write.atomic(
                "---\nname: \(name)\ndescription: fixture\n---\n\n# Fixture\n"
            )
        }

        return try body(
            Workspace.Context(
                root: Workspace.Root(checkout: checkout),
                home: File.Directory(try File.System.Canonical.resolve(home.path))
            )
        )
    }

    /// The installed projection directory for a fixture context.
    fileprivate static func projections(_ context: Workspace.Context) -> File.Directory {
        context.home[directory: ".claude"][directory: "skills"]
    }
}

extension Workspace.Context.Test.Unit {
    @Test
    func `install materializes documents and every canonical skill source`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()

            let skills = Workspace.Context.Test.projections(context)
            let institute = context.entry[directory: "swift-institute"]

            #expect(try context.diagnostics().isEmpty)
            #expect(
                try File.System.Link.Read.Target.target(
                    of: context.entry[directory: ".agents"].path / "skills"
                ) == skills.path
            )
            #expect(
                try File.System.Link.Read.Target.target(of: skills.path / "public-skill")
                    == institute[directory: "Skills"].path / "public-skill"
            )
            #expect(
                try File.System.Link.Read.Target.target(of: skills.path / "internal-skill")
                    == institute[directory: "Internal"][directory: "Skills"].path
                        / "internal-skill"
            )
            #expect(
                try File.System.Link.Read.Target.target(of: skills.path / "engagement-skill")
                    == institute[directory: "Engagement"][directory: "Skills"].path
                        / "engagement-skill"
            )
            #expect(
                try File.System.Link.Read.Target.target(of: skills.path / "rule-skill")
                    == context.entry[directory: "rule-institute"][directory: "Skills"].path
                        / "rule-skill"
            )
            // The projection is not reachable by walking down from the checkout,
            // which is the whole point: it is reachable from every root instead.
            #expect(!context.entry[directory: ".claude"].stat.exists)
            #expect(
                try File.System.Metadata.Permissions(
                    at: context.entry[file: "AGENTS.md"].path
                ) == .defaultFile
            )
            #expect(
                try File.System.Metadata.Permissions(
                    at: context.entry[file: "CLAUDE.md"].path
                ) == .defaultFile
            )
        }
    }

    @Test
    func `install is idempotent`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            try context.install()

            #expect(try context.diagnostics().isEmpty)
        }
    }

    @Test
    func `install refreshes its generated document`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            try context.root.checkout[directory: "Context"][file: "AGENTS.md"]
                .write.atomic("\(Workspace.Context.Test.marker)\n# Revised fixture\n")
            try context.root.checkout[directory: "Context"][file: "CLAUDE.md"]
                .write.atomic("\(Workspace.Context.Test.marker)\n@Revised.md\n")

            try context.install()

            #expect(try context.diagnostics().isEmpty)
        }
    }

    @Test
    func `install removes a retired generated skill projection`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            let institute = context.entry[directory: "swift-institute"]
            let skill = institute[directory: "Skills"][directory: "public-skill"]
            try skill[file: "SKILL.md"].delete()

            try context.install()

            let skills = Workspace.Context.Test.projections(context)
            #expect(!skills[file: "public-skill"].stat.exists)
            #expect(try context.diagnostics().isEmpty)
        }
    }
}

extension Workspace.Context.Test.`Edge Case` {
    @Test
    func `install rejects malformed canonical skill metadata before projecting`() throws {
        try Workspace.Context.Test.fixture { context in
            let institute = context.entry[directory: "swift-institute"]
            let publicSkills = institute[directory: "Skills"]
            let publicSkill = publicSkills[directory: "public-skill"]
            let skill = publicSkill[file: "SKILL.md"]
            try skill.write.atomic(
                """
                ---
                name: public-skill
                description: fixture
                layer: implementation
                ---
                # Fixture
                """
            )

            #expect(throws: Workspace.Error.self) {
                try context.install()
            }
            #expect(!context.home[directory: ".claude"].stat.exists)
        }
    }

    @Test
    func `install refuses an unmanaged root document before creating projections`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.entry[file: "AGENTS.md"].write.atomic("# Local instructions\n")

            #expect(throws: Workspace.Error.self) {
                try context.install()
            }
            #expect(
                !context.home[directory: ".claude"].stat.exists
            )
        }
    }

    @Test
    func `install preserves a user alias into a canonical skill root`() throws {
        try Workspace.Context.Test.fixture { context in
            try context.install()
            let institute = context.entry[directory: "swift-institute"]
            let canonical = institute[directory: "Skills"].path / "public-skill"
            let alias = Workspace.Context.Test.projections(context).path / "user-alias"
            try FileManager.default.createSymbolicLink(
                atPath: alias.description,
                withDestinationPath: canonical.description
            )

            try context.install()

            #expect(try File.System.Link.Read.Target.target(of: alias) == canonical)
            #expect(try context.diagnostics().isEmpty)
        }
    }

    @Test
    func `install projects the canonical roots this account carries and skips the rest`() throws {
        try Workspace.Context.Test.fixture(roots: ["public-skill"]) { context in
            try context.install()

            let skills = Workspace.Context.Test.projections(context)
            #expect(skills[file: "public-skill"].stat.exists)
            #expect(!skills[file: "internal-skill"].stat.exists)
            #expect(!skills[file: "engagement-skill"].stat.exists)
            #expect(!skills[file: "rule-skill"].stat.exists)
            #expect(try context.diagnostics().isEmpty)
        }
    }

    @Test
    func `install leaves a projection into a root it does not own alone`() throws {
        try Workspace.Context.Test.fixture(roots: ["public-skill"]) { context in
            try context.install()

            // A skill installed from somewhere outside every canonical Institute
            // root — a personal dotfiles checkout, say. Workspace does not know
            // it exists and must never remove it.
            let foreign = context.home[directory: "elsewhere"][directory: "foreign-skill"]
            try foreign.create.recursive()
            let alias = Workspace.Context.Test.projections(context).path / "foreign-skill"
            try FileManager.default.createSymbolicLink(
                atPath: alias.description,
                withDestinationPath: foreign.path.description
            )

            try context.install()

            #expect(try File.System.Link.Read.Target.target(of: alias) == foreign.path)
            #expect(try context.diagnostics().isEmpty)
        }
    }
}
